$NetBSD: patch-pyproject.toml,v 1.1 2024/01/20 10:21:27 adam Exp $

Fix build.

--- pyproject.toml.orig	2024-01-20 10:19:00.877645966 +0000
+++ pyproject.toml
@@ -52,7 +52,7 @@ path = 'flask_frozen/__init__.py'
 exclude = ['.*']
 
 [tool.hatch.build.targets.wheel]
-exclude = ['docs', 'tests']
+packages = ['flask_frozen']
 
 [tool.hatch.envs.doc]
 features = ['doc']
