# $NetBSD: Makefile,v 1.24 2026/09/06 15:08:56 taca Exp $

DISTNAME=	amq-protocol-2.9.0
CATEGORIES=	net

MAINTAINER=	pkgsrc-users@NetBSD.org
HOMEPAGE=	https://github.com/ruby-amqp/amq-protocol
COMMENT=	AMQP 0.9.1 encoder & decoder
LICENSE=	mit

.include "../../lang/ruby/gem.mk"
.include "../../mk/bsd.pkg.mk"
