# $NetBSD: Makefile,v 1.39 2026/09/06 11:02:58 markd Exp $

DISTNAME=	kdeedu-data-${KAPPSVER}
CATEGORIES=	misc

HOMEPAGE=	https://kde.org/applications/education/
COMMENT=	Common data for KDE Edu applications
LICENSE=	gnu-gpl-v2

.include "../../meta-pkgs/kde/applications.mk"

.include "../../graphics/hicolor-icon-theme/buildlink3.mk"
.include "../../x11/qt6-qtbase/buildlink3.mk"
.include "../../mk/bsd.pkg.mk"
