# $NetBSD: Makefile,v 1.28 2026/09/06 16:08:06 taca Exp $

DISTNAME=	tilt-2.9.0
CATEGORIES=	textproc

MAINTAINER=	pkgsrc-users@NetBSD.org
HOMEPAGE=	https://github.com/jeremyevans/tilt
COMMENT=	Generic interface to multiple Ruby template engines
LICENSE=	mit

USE_LANGUAGES=	# none

RUBYGEM_OPTIONS+=	--format-executable

.include "../../lang/ruby/gem.mk"
.include "../../mk/bsd.pkg.mk"
