# $NetBSD: Makefile,v 1.45 2026/09/06 14:22:29 taca Exp $

DISTNAME=	io-event-1.21.1
CATEGORIES=	devel

MAINTAINER=	pkgsrc-users@NetBSD.org
HOMEPAGE=	https://github.com/socketry/io-event
COMMENT=	Provides low level cross-platform primitives
LICENSE=	mit

.include "../../lang/ruby/gem.mk"
.include "../../mk/bsd.pkg.mk"
