$NetBSD: patch-Cargo.toml,v 1.6 2021/10/28 20:17:34 pin Exp $

Don't force ncurses backend

--- Cargo.toml.orig	2021-10-15 15:43:00.000000000 +0000
+++ Cargo.toml
@@ -47,7 +47,6 @@ strum_macros = "0.22.0"
 regex = "1"
 ioctl-rs = { version = "0.2", optional = true }
 serde_cbor = "0.11.2"
-pancurses = { version = "0.17.0", features = ["win32"] }
 
 [dependencies.cursive]
 version = "0.16.3"
