$NetBSD: patch-Cargo.toml,v 1.4 2022/03/08 09:25:17 wiz Exp $

Provide unpublished crate manually rather than fetch with git.

--- Cargo.toml.orig	2022-03-08 09:18:01.488392058 +0000
+++ Cargo.toml
@@ -35,10 +35,10 @@ bibutils-sys = { version = "0.1.1", opti
 byteorder = "1.4.3"
 cancellation = "0.1"
 cfg-if = "1.0.0"
-citeproc = { git = "https://github.com/cormacrelf/citeproc-rs", rev = "2ab195a1e6f84f0ff284813ece61dc62096abbfe", optional = true }
-citeproc-db = { git = "https://github.com/cormacrelf/citeproc-rs", rev = "2ab195a1e6f84f0ff284813ece61dc62096abbfe", optional = true }
-citeproc-io = { git = "https://github.com/cormacrelf/citeproc-rs", rev = "2ab195a1e6f84f0ff284813ece61dc62096abbfe", optional = true }
-csl = { git = "https://github.com/cormacrelf/citeproc-rs", rev = "2ab195a1e6f84f0ff284813ece61dc62096abbfe", optional = true }
+citeproc = { path = "../citeproc-rs/crates/citeproc", optional = true }
+citeproc-db = { path = "../citeproc-rs/crates/db", optional = true }
+citeproc-io = { path = "../citeproc-rs/crates/io", optional = true }
+csl = { path = "../citeproc-rs/crates/csl", optional = true }
 crossbeam-channel = "0.5.2"
 cstree = "0.6.1"
 dashmap = "5.1.0"
