$NetBSD: patch-Cargo.toml,v 1.14 2022/02/03 21:46:51 pin Exp $

Don't pull vendored version, use pkgsrc LuaJIT2

--- Cargo.toml.orig	2022-02-03 04:56:06.000000000 +0000
+++ Cargo.toml
@@ -71,7 +71,6 @@ features = ['serde']
 version = '0.7'
 features = [
     'luajit',
-    'vendored',
     'serialize',
     'send',
 ]
