# $NetBSD: Makefile,v 1.21 2026/09/06 15:11:34 taca Exp $

DISTNAME=	domain_name-0.6.20260902
CATEGORIES=	net

MAINTAINER=	minskim@NetBSD.org
HOMEPAGE=	https://github.com/knu/ruby-domain_name
COMMENT=	Domain name manipulation library for Ruby
LICENSE=	2-clause-bsd

.include "../../lang/ruby/gem.mk"
.include "../../mk/bsd.pkg.mk"
