$NetBSD: patch-Cargo.toml,v 1.3 2024/01/18 14:09:27 hauke Exp $

Bump openssl version

--- Cargo.toml.orig	2023-11-15 09:41:14.000000000 +0000
+++ Cargo.toml
@@ -139,10 +139,10 @@ cookie = "0.16.2"
 cookie_store = "0.19.1"
 
 # Used by U2F, JWT and PostgreSQL
-openssl = "=0.10.57"
+openssl = "=0.10.60"
 # Set openssl-sys fixed to v0.9.92 to prevent building issues with musl, arm and 32bit pointer width
 # It will force add a dynamically linked library which prevents the build from being static
-openssl-sys = "=0.9.92"
+openssl-sys = "=0.9.96"
 
 # CLI argument parsing
 pico-args = "0.5.0"
