# $NetBSD: Makefile,v 1.1 2026/09/06 09:25:21 markd Exp $

DISTNAME=	xsimd-14.3.0
CATEGORIES=	devel
MASTER_SITES=	${MASTER_SITE_GITHUB:=xtensor-stack/}

MAINTAINER=	pkgsrc-users@NetBSD.org
HOMEPAGE=	https://github.com/xtensor-stack/xsimd
COMMENT=	C++ wrappers for SIMD intrinsics
LICENSE=	modified-bsd

USE_CXX_FEATURES=	c++17
USE_LANGUAGES=		c c++

.include "../../devel/cmake/build.mk"

.include "../../mk/bsd.pkg.mk"
